// Homepage
const BRAND_LEAD_APPLICANT_CREATE_INIT = 'BRAND_LEAD:APPLICANT_CREATE:INIT';
const BRAND_LEAD_APPLICANT_CREATE_SUCCESS = 'BRAND_LEAD:APPLICANT_CREATE:SUCCESS';
const BRAND_LEAD_APPLICANT_CREATE_FAIL = 'BRAND_LEAD:APPLICANT_CREATE:FAIL';
const BRAND_LEAD_APPLICATION_DETAIL_FETCH_INIT = 'BRAND_LEAD:APPLICATION_DETAIL:FETCH:INIT';
const BRAND_LEAD_APPLICATION_DETAIL_FETCH_SUCCESS = 'BRAND_LEAD:APPLICATION_DETAIL:FETCH:SUCCESS';
const BRAND_LEAD_APPLICATION_DETAIL_FETCH_FAIL = 'BRAND_LEAD:APPLICATION_DETAIL:FETCH:FAIL';
const BRAND_LEAD_APPLICANT_DETAIL_UPDATE_INIT = 'BRAND_LEAD:APPLICANT_DETAIL:UPDATE:INIT';
const BRAND_LEAD_APPLICANT_DETAIL_UPDATE_SUCCESS = 'BRAND_LEAD:APPLICANT_DETAIL:UPDATE:SUCCESS';
const BRAND_LEAD_APPLICANT_DETAIL_UPDATE_FAIL = 'BRAND_LEAD:APPLICANT_DETAIL:UPDATE:FAIL';
const BRAND_LEAD_BUSINESS_DETAIL_UPDATE_INIT = 'BRAND_LEAD:BUSINESS_DETAIL:UPDATE:INIT';
const BRAND_LEAD_BUSINESS_DETAIL_UPDATE_SUCCESS = 'BRAND_LEAD:BUSINESS_DETAIL:UPDATE:SUCCESS';
const BRAND_LEAD_BUSINESS_DETAIL_UPDATE_FAIL = 'BRAND_LEAD:BUSINESS_DETAIL:UPDATE:FAIL';
const BRAND_LEAD_BRAND_DETAIL_UPDATE_INIT = 'BRAND_LEAD:BRAND_DETAIL:UPDATE:INIT';
const BRAND_LEAD_BRAND_DETAIL_UPDATE_SUCCESS = 'BRAND_LEAD:BRAND_DETAIL:UPDATE:SUCCESS';
const BRAND_LEAD_BRAND_DETAIL_UPDATE_FAIL = 'BRAND_LEAD:BRAND_DETAIL:UPDATE:FAIL';
const BRAND_LEAD_BRAND_STATUS_UPDATE_INIT = 'BRAND_LEAD:BRAND_STATUS:UPDATE:INIT';
const BRAND_LEAD_BRAND_STATUS_UPDATE_SUCCESS = 'BRAND_LEAD:BRAND_STATUS:UPDATE:SUCCESS';
const BRAND_LEAD_BRAND_STATUS_UPDATE_FAIL = 'BRAND_LEAD:BRAND_STATUS:UPDATE:FAIL';
const BRAND_LEAD_BRAND_DOCUMENT_CONFIG_FETCH_INIT = 'BRAND_LEAD:BRAND_DOCUMENT_CONFIG:FETCH:INIT';
const BRAND_LEAD_BRAND_DOCUMENT_CONFIG_FETCH_SUCCESS = 'BRAND_LEAD:BRAND_DOCUMENT_CONFIG:FETCH:SUCCESS';
const BRAND_LEAD_BRAND_DOCUMENT_CONFIG_FETCH_FAIL = 'BRAND_LEAD:BRAND_DOCUMENT_CONFIG:FETCH:FAIL';
const BRAND_LEAD_BRAND_DOCUMENT_PRESIGNED_URL_FETCH_INIT = 'BRAND_LEAD:BRAND_DOCUMENT_PRESIGNED_URL:FETCH:INIT';
const BRAND_LEAD_BRAND_DOCUMENT_PRESIGNED_URL_FETCH_SUCCESS = 'BRAND_LEAD:DOCUMENT_PRESIGNED_URL:FETCH:SUCCESS';
const BRAND_LEAD_BRAND_DOCUMENT_PRESIGNED_URL_FETCH_FAIL = 'BRAND_LEAD:DOCUMENT_PRESIGNED_URL:FETCH:FAIL';
const BRAND_LEAD_BRAND_DOCUMENT_METADATA_POST_INIT = 'BRAND_LEAD:DOCUMENT_METADATA:POST:INIT';
const BRAND_LEAD_BRAND_DOCUMENT_METADATA_POST_SUCCESS = 'BRAND_LEAD:DOCUMENT_METADATA:POST:SUCCESS';
const BRAND_LEAD_BRAND_DOCUMENT_METADATA_POST_FAIL = 'BRAND_LEAD:DOCUMENT_METADATA:POST:FAIL';
const BRAND_LEAD_BRAND_DOCUMENT_LIST_FETCH_INIT = 'BRAND_LEAD:DOCUMENT_LIST:FETCH:INIT';
const BRAND_LEAD_BRAND_DOCUMENT_LIST_FETCH_SUCCESS = 'BRAND_LEAD:DOCUMENT_LIST:FETCH:SUCCESS';
const BRAND_LEAD_BRAND_DOCUMENT_LIST_FETCH_FAIL = 'BRAND_LEAD:DOCUMENT_LIST:FETCH:FAIL';
const BRAND_LEAD_DETAIL_UPDATE_CLEAR = 'BRAND_LEAD:DETAIL:UPDATE:CLEAR';
const BRAND_LEAD_BRAND_DOCUMENT_STATUS_UPDATE_INIT = 'BRAND_LEAD:BRAND_DOCUMENT:STATUS_UPDATE:INIT';
const BRAND_LEAD_BRAND_DOCUMENT_STATUS_UPDATE_SUCCESS = 'BRAND_LEAD:BRAND_DOCUMENT:STATUS_UPDATE:SUCCESS';
const BRAND_LEAD_BRAND_DOCUMENT_STATUS_UPDATE_FAIL = 'BRAND_LEAD:BRAND_DOCUMENT:STATUS_UPDATE:FAIL';
const BRAND_LEAD_DOCUMENT_FILE_VIEW_INIT = 'BRAND_LEAD:DOCUMENT_FILE:VIEW:INIT';
const BRAND_LEAD_DOCUMENT_FILE_VIEW_SUCCESS = 'BRAND_LEAD:DOCUMENT_FILE:VIEW:SUCCESS';
const BRAND_LEAD_DOCUMENT_FILE_VIEW_FAIL = 'BRAND_LEAD:DOCUMENT_FILE:VIEW:FAIL';
const BRAND_LEAD_DOCUMENT_FILE_DELETE_INIT = 'BRAND_LEAD:DOCUMENT_FILE:DELETE:INIT';
const BRAND_LEAD_DOCUMENT_FILE_DELETE_SUCCESS = 'BRAND_LEAD:DOCUMENT_FILE:DELETE:SUCCESS';
const BRAND_LEAD_DOCUMENT_FILE_DELETE_FAIL = 'BRAND_LEAD:DOCUMENT_FILE:DELETE:FAIL';
const BRAND_LEAD_DOCUMENT_CONFIG_DATA_CLEAR = 'BRAND_LEAD:DOCUMENT:CONFIG:DATA:CLEAR';

// brands-v2

const BRAND_LEAD_DETAIL_FORM_UPDATE_INIT = 'BRAND_LEAD:DETAIL_FORM:UPDATE:INIT';
const BRAND_LEAD_DETAIL_FORM_UPDATE_SUCCESS = 'BRAND_LEAD:DETAIL_FORM:UPDATE:SUCCESS';
const BRAND_LEAD_DETAIL_FORM_UPDATE_FAIL = 'BRAND_LEAD:DETAIL_FORM:UPDATE:FAIL';
const BRAND_LEAD_APPLICANT_DETAIL_INIT = 'BRAND_LEAD:APPLICANT_DETAIL:INIT';
const BRAND_LEAD_APPLICANT_DETAIL_SUCCESS = 'BRAND_LEAD:APPLICANT_DETAIL:SUCCESS';
const BRAND_LEAD_APPLICANT_DETAIL_FAIL = 'BRAND_LEAD:APPLICANT_DETAIL:FAIL';
const BRAND_LEAD_LIST_FETCH_INIT = 'BRAND_LEAD:LIST_FETCH:INIT';
const BRAND_LEAD_LIST_FETCH_SUCCESS = 'BRAND_LEAD:LIST_FETCH:SUCCESS';
const BRAND_LEAD_LIST_FETCH_FAIL = 'BRAND_LEAD:LIST_FETCH:FAIL';
const BRAND_LEAD_DETAIL_FETCH_INIT = 'BRAND_LEAD:DETAIL_FETCH:INIT';
const BRAND_LEAD_DETAIL_FETCH_SUCCESS = 'BRAND_LEAD:DETAIL_FETCH:SUCCESS';
const BRAND_LEAD_DETAIL_FETCH_FAIL = 'BRAND_LEAD:DETAIL_FETCH:FAIL';
const BRAND_LEAD_PERFORMANCE_FETCH_INIT = 'BRAND_LEAD:PERFORMANCE_FETCH:INIT';
const BRAND_LEAD_PERFORMANCE_FETCH_SUCCESS = 'BRAND_LEAD:PERFORMANCE_FETCH:SUCCESS';
const BRAND_LEAD_PERFORMANCE_FETCH_FAIL = 'BRAND_LEAD:PERFORMANCE_FETCH:FAIL';
const BRAND_LEAD_PERFORMANCE_UPDATE_INIT = 'BRAND_LEAD:PERFORMANCE_UPDATE:INIT';
const BRAND_LEAD_PERFORMANCE_UPDATE_SUCCESS = 'BRAND_LEAD:PERFORMANCE_UPDATE:SUCCESS';
const BRAND_LEAD_PERFORMANCE_UPDATE_FAIL = 'BRAND_LEAD:PERFORMANCE_UPDATE:FAIL';
const BRAND_LEAD_COMMUNICATIONS_DETAIL_FETCH_INIT = 'BRAND_LEAD:COMMUNICATIONS_FETCH:INIT';
const BRAND_LEAD_COMMUNICATIONS_DETAIL_FETCH_SUCCESS = 'BRAND_LEAD:COMMUNICATIONS_FETCH:SUCCESS';
const BRAND_LEAD_COMMUNICATIONS_DETAIL_FETCH_FAIL = 'BRAND_LEAD:COMMUNICATIONS_FETCH:FAIL';
const BRAND_COMMUNICATION_GET_ADDRESSES_INIT = 'BRAND_LEAD:COMMUNICATIONS:ADDRESSES_FETCH:INIT';
const BRAND_COMMUNICATION_GET_ADDRESSES_SUCCESS = 'BRAND_LEAD:COMMUNICATIONS:ADDRESSES_FETCH:SUCCESS';
const BRAND_COMMUNICATION_GET_ADDRESSES_FAIL = 'BRAND_LEAD:COMMUNICATIONS:ADDRESSES_FETCH:FAIL';
const BRAND_CREATE_BRAND_INIT = 'BRAND:CREATE_BRAND:INIT';
const BRAND_CREATE_BRAND_SUCCESS = 'BRAND:CREATE_BRAND:SUCCESS';
const BRAND_CREATE_BRAND_FAIL = 'BRAND:CREATE_BRAND:FAIL';
const BRAND_APPLICANT_LIST_FETCH_INIT = 'BRAND:APPLICANT_LIST:FETCH:INIT';
const BRAND_APPLICANT_LIST_FETCH_SUCCESS = 'BRAND:APPLICANT_LIST:FETCH:SUCCESS';
const BRAND_APPLICANT_LIST_FETCH_FAIL = 'BRAND:APPLICANT_LIST:FETCH:FAIL';
const BRAND_BUSINESS_DETAILS_FETCH_INIT = 'BRAND:BUSINESS_DETAILS:FETCH:INIT';
const BRAND_BUSINESS_DETAILS_FETCH_SUCCESS = 'BRAND:BUSINESS_DETAILS:FETCH:SUCCESS';
const BRAND_BUSINESS_DETAILS_FETCH_FAIL = 'BRAND:BUSINESS_DETAILS:FETCH:FAIL';
const BRAND_BUSINESS_DETAILS_UPDATE_INIT = 'BRAND:BUSINESS_DETAILS:UPDATE:INIT';
const BRAND_BUSINESS_DETAILS_UPDATE_SUCCESS = 'BRAND:BUSINESS_DETAILS:UPDATE:SUCCESS';
const BRAND_BUSINESS_DETAILS_UPDATE_FAIL = 'BRAND:BUSINESS_DETAILS:UPDATE:FAIL';
const BRAND_APPLICANT_BASIC_INFO_FETCH_INIT = 'BRAND:APPLICANT_BASIC_INFO:FETCH:INIT';
const BRAND_APPLICANT_BASIC_INFO_FETCH_SUCCESS = 'BRAND:APPLICANT_BASIC_INFO:FETCH:SUCCESS';
const BRAND_APPLICANT_BASIC_INFO_FETCH_FAIL = 'BRAND:APPLICANT_BASIC_INFO:FETCH:FAIL';
const BRAND_STATUS_UPDATE_INIT = 'BRAND:STATUS_UPDATE:INIT';
const BRAND_STATUS_UPDATE_SUCCESS = 'BRAND:STATUS_UPDATE:SUCCESS';
const BRAND_STATUS_UPDATE__FAIL = 'BRAND:STATUS_UPDATE:FAIL';
const BRAND_BANKING_BANKS_FETCH_INIT = 'BRAND:BANKING:BANKS_FETCH:INIT';
const BRAND_BANKING_BANKS_FETCH_SUCCESS = 'BRAND:BANKING:BANKS_FETCH:SUCCESS';
const BRAND_BANKING_BANKS_FETCH_FAIL = 'BRAND:BANKING:BANKS_FETCH:FAIL';
const BRAND_BANKING_ACCOUNTS_FETCH_INIT = 'BRAND:BANKING:ACCOUNTS_FETCH:INIT';
const BRAND_BANKING_ACCOUNTS_FETCH_SUCCESS = 'BRAND:BANKING:ACCOUNTS_FETCH:SUCCESS';
const BRAND_BANKING_ACCOUNTS_FETCH_FAIL = 'BRAND:BANKING:ACCOUNTS_FETCH:FAIL';
const BRAND_BANKING_ADD_ACCOUNT_INIT = 'BRAND:BANKING:ADD_ACCOUNT:INIT';
const BRAND_BANKING_ADD_ACCOUNT_SUCCESS = 'BRAND:BANKING:ADD_ACCOUNT:SUCCESS';
const BRAND_BANKING_ADD_ACCOUNT_FAIL = 'BRAND:BANKING:ADD_ACCOUNT:FAIL';
const BRAND_BANKING_UPDATE_ACCOUNT_INIT = 'BRAND:BANKING:UPDATE_ACCOUNT:INIT';
const BRAND_BANKING_UPDATE_ACCOUNT_SUCCESS = 'BRAND:BANKING:UPDATE_ACCOUNT:SUCCESS';
const BRAND_BANKING_UPDATE_ACCOUNT_FAIL = 'BRAND:BANKING:UPDATE_ACCOUNT:FAIL';
const BRAND_BANKING_DOCUMENT_FETCH_INIT = 'BRAND:BANKING:DOCUMENT_FETCH:INIT';
const BRAND_BANKING_DOCUMENT_FETCH_SUCCESS = 'BRAND:BANKING:DOCUMENT_FETCH:SUCCESS';
const BRAND_BANKING_DOCUMENT_FETCH_FAIL = 'BRAND:BANKING:DOCUMENT_FETCH:FAIL';
const BRAND_BANKING_DOCUMENT_TYPE_FETCH_INIT = 'BRAND:BANKING:DOCUMENT_TYPE:FETCH:INIT';
const BRAND_BANKING_DOCUMENT_TYPE_FETCH_SUCCESS = 'BRAND:BANKING:DOCUMENT_TYPE:FETCH:SUCCESS';
const BRAND_BANKING_DOCUMENT_TYPE_FETCH_FAIL = 'BRAND:BANKING:DOCUMENT_TYPE:FETCH:FAIL';
const BRAND_APPLICANT_INFO_STORE = 'BRANDS:APPLICANT_INFO:STORE';
const BRAND_BANKING_CLEAR_ACCOUNTS = 'BRAND:BANKING:CLEAR_ACCOUNTS';
const BRAND_BANKING_DOCUMENT_PARSE_INIT = 'BRAND:BANKING:DOCUMENT:PARSE:INIT';
const BRAND_BANKING_DOCUMENT_PARSE_SUCCESS = 'BRAND:BANKING:DOCUMENT:PARSE:SUCCESS';
const BRAND_BANKING_DOCUMENT_PARSE_FAIL = 'BRAND:BANKING:DOCUMENT:PARSE:FAIL';

// Brand Application Financials
const BRAND_FINANCIAL_OVERVIEW_FETCH_INIT = 'BRAND:FINANCIAL:OVERVIEW_FETCH:INIT';
const BRAND_FINANCIAL_OVERVIEW_FETCH_SUCCESS = 'BRAND:FINANCIAL:OVERVIEW_FETCH:SUCCESS';
const BRAND_FINANCIAL_OVERVIEW_FETCH_FAIL = 'BRAND:FINANCIAL:OVERVIEW_FETCH:FAIL';

const BRAND_FINANCIAL_SHAREHOLDING_FETCH_INIT = 'BRAND:FINANCIAL:SHAREHOLDING_FETCH:INIT';
const BRAND_FINANCIAL_SHAREHOLDING_FETCH_SUCCESS = 'BRAND:FINANCIAL:SHAREHOLDING_FETCH:SUCCESS';
const BRAND_FINANCIAL_SHAREHOLDING_FETCH_FAIL = 'BRAND:FINANCIAL:SHAREHOLDING_FETCH:FAIL';

const BRAND_FINANCIAL_SHAREHOLDING_SUMMARY_FETCH_INIT = 'BRAND:FINANCIAL:SHAREHOLDING_SUMMARY_FETCH:INIT';
const BRAND_FINANCIAL_SHAREHOLDING_SUMMARY_FETCH_SUCCESS = 'BRAND:FINANCIAL:SHAREHOLDING_SUMMARY_FETCH:SUCCESS';
const BRAND_FINANCIAL_SHAREHOLDING_SUMMARY_FETCH_FAIL = 'BRAND:FINANCIAL:SHAREHOLDING_SUMMARY_FETCH:FAIL';

const BRAND_FINANCIAL_SECURITIES_ALLOTMENT_FETCH_INIT = 'BRAND:FINANCIAL:SECURITIES_ALLOTMENT_FETCH:INIT';
const BRAND_FINANCIAL_SECURITIES_ALLOTMENT_FETCH_SUCCESS = 'BRAND:FINANCIAL:SECURITIES_ALLOTMENT_FETCH:SUCCESS';
const BRAND_FINANCIAL_SECURITIES_ALLOTMENT_FETCH_FAIL = 'BRAND:FINANCIAL:SECURITIES_ALLOTMENT_FETCH:FAIL';

const BRAND_FINANCIAL_PROFIT_AND_LOSS_FETCH_INIT = 'BRAND:FINANCIAL:PROFIT_AND_LOSS_FETCH:INIT';
const BRAND_FINANCIAL_PROFIT_AND_LOSS_FETCH_SUCCESS = 'BRAND:FINANCIAL:PROFIT_AND_LOSS_FETCH:SUCCESS';
const BRAND_FINANCIAL_PROFIT_AND_LOSS_FETCH_FAIL = 'BRAND:FINANCIAL:PROFIT_AND_LOSS_FETCH:FAIL';

const BRAND_FINANCIAL_BALANCE_SHEET_FETCH_INIT = 'BRAND:FINANCIAL:BALANCE_SHEET_FETCH:INIT';
const BRAND_FINANCIAL_BALANCE_SHEET_FETCH_SUCCESS = 'BRAND:FINANCIAL:BALANCE_SHEET_FETCH:SUCCESS';
const BRAND_FINANCIAL_BALANCE_SHEET_FETCH_FAIL = 'BRAND:FINANCIAL:BALANCE_SHEET_FETCH:FAIL';

const BRAND_FINANCIAL_CASH_FLOW_FETCH_INIT = 'BRAND:FINANCIAL:CASH_FLOW_FETCH:INIT';
const BRAND_FINANCIAL_CASH_FLOW_FETCH_SUCCESS = 'BRAND:FINANCIAL:CASH_FLOW_FETCH:SUCCESS';
const BRAND_FINANCIAL_CASH_FLOW_FETCH_FAIL = 'BRAND:FINANCIAL:CASH_FLOW_FETCH:FAIL';

const BRAND_FINANCIAL_CHARGES_FETCH_INIT = 'BRAND:FINANCIAL:CHARGES_FETCH:INIT';
const BRAND_FINANCIAL_CHARGES_FETCH_SUCCESS = 'BRAND:FINANCIAL:CHARGES_FETCH:SUCCESS';
const BRAND_FINANCIAL_CHARGES_FETCH_FAIL = 'BRAND:FINANCIAL:CHARGES_FETCH:FAIL';

const BRAND_FINANCIAL_LEGAL_HISTORY_FETCH_INIT = 'BRAND:FINANCIAL:LEGAL_HISTORY_FETCH:INIT';
const BRAND_FINANCIAL_LEGAL_HISTORY_FETCH_SUCCESS = 'BRAND:FINANCIAL:LEGAL_HISTORY_FETCH:SUCCESS';
const BRAND_FINANCIAL_LEGAL_HISTORY_FETCH_FAIL = 'BRAND:FINANCIAL:LEGAL_HISTORY_FETCH:FAIL';

const BRANDS_FETCH_FINANCIALS_INIT = 'BRANDS:FINANCIALS_FETCH:INIT';
const BRANDS_FETCH_FINANCIALS_SUCCESS = 'BRANDS:FINANCIALS_FETCH:SUCCESS';
const BRANDS_FETCH_FINANCIALS_FAIL = 'BRANDS:FINANCIALS_FETCH:FAIL';

// Patron
const PATRON_LEAD_APPLICANT_CREATE_INIT = 'PATRON_LEAD:APPLICANT_CREATE:INIT';
const PATRON_LEAD_APPLICANT_CREATE_SUCCESS = 'PATRON_LEAD:APPLICANT_CREATE:SUCCESS';
const PATRON_LEAD_APPLICANT_CREATE_FAIL = 'PATRON_LEAD:APPLICANT_CREATE:FAIL';
const PATRON_LEAD_PATRON_DETAIL_FETCH_INIT = 'PATRON_LEAD:PATRON_DETAIL:FETCH:INIT';
const PATRON_LEAD_PATRON_DETAIL_FETCH_SUCCESS = 'PATRON_LEAD:PATRON_DETAIL:FETCH:SUCCESS';
const PATRON_LEAD_PATRON_DETAIL_FETCH_FAIL = 'PATRON_LEAD:PATRON_DETAIL:FETCH:FAIL';
const PATRON_LEAD_APPLICATION_DETAIL_UPDATE_INIT = 'PATRON_LEAD:APPLICATION_DETAIL:UPDATE:INIT';
const PATRON_LEAD_APPLICATION_DETAIL_UPDATE_SUCCESS = 'PATRON_LEAD:APPLICATION_DETAIL:UPDATE:SUCCESS';
const PATRON_LEAD_APPLICATION_DETAIL_UPDATE_FAIL = 'PATRON_LEAD:APPLICATION_DETAIL:UPDATE:FAIL';
const PATRON_LEAD_ENTITY_DETAIL_UPDATE_INIT = 'PATRON_LEAD:ENTITY_DETAIL:UPDATE:INIT';
const PATRON_LEAD_ENTITY_DETAIL_UPDATE_SUCCESS = 'PATRON_LEAD:ENTITY_DETAIL:UPDATE:SUCCESS';
const PATRON_LEAD_ENTITY_DETAIL_UPDATE_FAIL = 'PATRON_LEAD:ENTITY_DETAIL:UPDATE:FAIL';
const PATRON_LEAD_PATRON_STATUS_UPDATE_INIT = 'PATRON_LEAD:PATRON_STATUS:UPDATE:INIT';
const PATRON_LEAD_PATRON_STATUS_UPDATE_SUCCESS = 'PATRON_LEAD:PATRON_STATUS:UPDATE:SUCCESS';
const PATRON_LEAD_PATRON_STATUS_UPDATE_FAIL = 'PATRON_LEAD:PATRON_STATUS:UPDATE:FAIL';
const PATRON_LEAD_DETAIL_UPDATE_CLEAR = 'PATRON_LEAD:DETAIL:UPDATE:CLEAR';
const PATRON_LEAD_PATRON_DOCUMENT_CONFIG_FETCH_INIT = 'PATRON_LEAD:PATRON_DOCUMENT_CONFIG:FETCH:INIT';
const PATRON_LEAD_PATRON_DOCUMENT_CONFIG_FETCH_SUCCESS = 'PATRON_LEAD:PATRON_DOCUMENT_CONFIG:FETCH:SUCCESS';
const PATRON_LEAD_PATRON_DOCUMENT_CONFIG_FETCH_FAIL = 'PATRON_LEAD:PATRON_DOCUMENT_CONFIG:FETCH:FAIL';
const PATRON_LEAD_PATRON_DOCUMENT_PRESIGNED_URL_FETCH_INIT = 'PATRON_LEAD:PATRON_DOCUMENT_PRESIGNED_URL:FETCH:INIT';
const PATRON_LEAD_PATRON_DOCUMENT_PRESIGNED_URL_FETCH_SUCCESS = 'PATRON_LEAD:DOCUMENT_PRESIGNED_URL:FETCH:SUCCESS';
const PATRON_LEAD_PATRON_DOCUMENT_PRESIGNED_URL_FETCH_FAIL = 'PATRON_LEAD:DOCUMENT_PRESIGNED_URL:FETCH:FAIL';
const PATRON_LEAD_PATRON_DOCUMENT_METADATA_POST_INIT = 'PATRON_LEAD:DOCUMENT_METADATA:POST:INIT';
const PATRON_LEAD_PATRON_DOCUMENT_METADATA_POST_SUCCESS = 'PATRON_LEAD:DOCUMENT_METADATA:POST:SUCCESS';
const PATRON_LEAD_PATRON_DOCUMENT_METADATA_POST_FAIL = 'PATRON_LEAD:DOCUMENT_METADATA:POST:FAIL';
const PATRON_LEAD_PATRON_DOCUMENT_LIST_FETCH_INIT = 'PATRON_LEAD:DOCUMENT_LIST:FETCH:INIT';
const PATRON_LEAD_PATRON_DOCUMENT_LIST_FETCH_SUCCESS = 'PATRON_LEAD:DOCUMENT_LIST:FETCH:SUCCESS';
const PATRON_LEAD_PATRON_DOCUMENT_LIST_FETCH_FAIL = 'PATRON_LEAD:DOCUMENT_LIST:FETCH:FAIL';
const PATRON_LEAD_DOCUMENT_FILE_VIEW_INIT = 'PATRON_LEAD:DOCUMENT_FILE:VIEW:INIT';
const PATRON_LEAD_DOCUMENT_FILE_VIEW_SUCCESS = 'PATRON_LEAD:DOCUMENT_FILE:VIEW:SUCCESS';
const PATRON_LEAD_DOCUMENT_FILE_VIEW_FAIL = 'PATRON_LEAD:DOCUMENT_FILE:VIEW:FAIL';
const PATRON_LEAD_DOCUMENT_FILE_DELETE_INIT = 'PATRON_LEAD:DOCUMENT_FILE:DELETE:INIT';
const PATRON_LEAD_DOCUMENT_FILE_DELETE_SUCCESS = 'PATRON_LEAD:DOCUMENT_FILE:DELETE:SUCCESS';
const PATRON_LEAD_DOCUMENT_FILE_DELETE_FAIL = 'PATRON_LEAD:DOCUMENT_FILE:DELETE:FAIL';
const PATRON_LEAD_PATRON_DOCUMENT_STATUS_UPDATE_INIT = 'PATRON_LEAD:PATRON_DOCUMENT:STATUS:UPDATE:INIT';
const PATRON_LEAD_PATRON_DOCUMENT_STATUS_UPDATE_SUCCESS = 'PATRON_LEAD:PATRON_DOCUMENT:STATUS:UPDATE:SUCCESS';
const PATRON_LEAD_PATRON_DOCUMENT_STATUS_UPDATE_FAIL = 'PATRON_LEAD:PATRON_DOCUMENT:STATUS:UPDATE:FAIL';
const PATRON_LEAD_DOCUMENT_CONFIG_DATA_CLEAR = 'PATRON_LEAD:DOCUMENT:CONFIG:DATA:CLEAR';

// patrons
const PATRON_LEAD_LIST_FETCH_INIT = 'PATRON_LEAD:LIST_FETCH:INIT';
const PATRON_LEAD_LIST_FETCH_SUCCESS = 'PATRON_LEAD:LIST_FETCH:SUCCESS';
const PATRON_LEAD_LIST_FETCH_FAIL = 'PATRON_LEAD:LIST_FETCH:FAIL';
const PATRON_CREATE_PATRON_INIT = 'PATRON:CREATE_PATRON:INIT';
const PATRON_CREATE_PATRON_SUCCESS = 'PATRON:CREATE_PATRON:SUCCESS';
const PATRON_CREATE_PATRON_FAIL = 'PATRON:CREATE_PATRON:FAIL';
const GENERIC_ADD_NUMBER_INIT = 'GENERIC:ADD_NUMBER:INIT';
const GENERIC_ADD_NUMBER_SUCCESS = 'GENERIC:ADD_NUMBER:SUCCESS';
const GENERIC_ADD_NUMBER_FAIL = 'GENERIC:ADD_NUMBER:FAIL';
const GENERIC_ADD_EMAIL_INIT = 'GENERIC:ADD_EMAIL:INIT';
const GENERIC_ADD_EMAIL_SUCCESS = 'GENERIC:ADD_EMAIL:SUCCESS';
const GENERIC_ADD_EMAIL_FAIL = 'GENERIC:ADD_EMAIL:FAIL';
const GENERIC_ADD_ADDRESS_INIT = 'GENERIC:ADD_ADDRESS:INIT';
const GENERIC_ADD_ADDRESS_SUCCESS = 'GENERIC:ADD_ADDRESS:SUCCESS';
const GENERIC_ADD_ADDRESS_FAIL = 'GENERIC:ADD_ADDRESS:FAIL';
const GENERIC_GET_PHONES_INIT = 'GENERIC:GET_PHONES:INIT';
const GENERIC_GET_PHONES_SUCCESS = 'GENERIC:GET_PHONES:SUCCESS';
const GENERIC_GET_PHONES_FAIL = 'GENERIC:GET_PHONES:FAIL';
const GENERIC_GET_EMAILS_INIT = 'GENERIC:GET_EMAILS:INIT';
const GENERIC_GET_EMAILS_SUCCESS = 'GENERIC:GET_EMAILS:SUCCESS';
const GENERIC_GET_EMAILS_FAIL = 'GENERIC:GET_EMAILS:FAIL';
const GENERIC_UPDATE_NUMBER_INIT = 'GENERIC:UPDATE_NUMBER:INIT';
const GENERIC_UPDATE_NUMBER_SUCCESS = 'GENERIC:UPDATE_NUMBER:SUCCESS';
const GENERIC_UPDATE_NUMBER_FAIL = 'GENERIC:UPDATE_NUMBER:FAIL';
const GENERIC_UPDATE_EMAIL_INIT = 'GENERIC:UPDATE_EMAIL:INIT';
const GENERIC_UPDATE_EMAIL_SUCCESS = 'GENERIC:UPDATE_EMAIL:SUCCESS';
const GENERIC_UPDATE_EMAIL_FAIL = 'GENERIC:UPDATE_EMAIL:FAIL';
const GENERIC_GET_ADDRESSES_INIT = 'GENERIC:GET_ADDRESSES:INIT';
const GENERIC_GET_ADDRESSES_SUCCESS = 'GENERIC:GET_ADDRESSES:SUCCESS';
const GENERIC_GET_ADDRESSES_FAIL = 'GENERIC:GET_ADDRESSES:FAIL';
const GENERIC_UPDATE_ADDRESS_INIT = 'GENERIC:UPDATE_ADDRESS:INIT';
const GENERIC_UPDATE_ADDRESS_SUCCESS = 'GENERIC:UPDATE_ADDRESS:SUCCESS';
const GENERIC_UPDATE_ADDRESS_FAIL = 'GENERIC:UPDATE_ADDRESS:FAIL';
const PATRON_LEAD_DETAIL_FETCH_INIT = 'PATRON_LEAD:DETAIL_FETCH:INIT';
const PATRON_LEAD_DETAIL_FETCH_SUCCESS = 'PATRON_LEAD:DETAIL_FETCH:SUCCESS';
const PATRON_LEAD_DETAIL_FETCH_FAIL = 'PATRON_LEAD:DETAIL_FETCH:FAIL';
const PATRON_LEAD_CUSTOMER_DETAIL_FETCH_INIT = 'PATRON_LEAD:CUSTOMER:DETAIL_FETCH:INIT';
const PATRON_LEAD_CUSTOMER_DETAIL_FETCH_SUCCESS = 'PATRON_LEAD:CUSTOMER:DETAIL_FETCH:SUCCESS';
const PATRON_LEAD_CUSTOMER_DETAIL_FETCH_FAIL = 'PATRON_LEAD:CUSTOMER:DETAIL_FETCH:FAIL';
const PATRON_LEAD_INVESTOR_DETAIL_FETCH_INIT = 'PATRON_LEAD:INVESTOR:DETAIL_FETCH:INIT';
const PATRON_LEAD_INVESTOR_DETAIL_FETCH_SUCCESS = 'PATRON_LEAD:INVESTOR:DETAIL_FETCH:SUCCESS';
const PATRON_LEAD_INVESTOR_DETAIL_FETCH_FAIL = 'PATRON_LEAD:INVESTOR:DETAIL_FETCH:FAIL';
const PATRON_LEAD_CUSTOMER_DETAIL_SAVE_INIT = 'PATRON_LEAD:CUSTOMER:DETAIL_SAVE:INIT';
const PATRON_LEAD_CUSTOMER_DETAIL_SAVE_SUCCESS = 'PATRON_LEAD:CUSTOMER:DETAIL_SAVE:SUCCESS';
const PATRON_LEAD_CUSTOMER_DETAIL_SAVE_FAIL = 'PATRON_LEAD:CUSTOMER:DETAIL_SAVE:FAIL';
const PATRON_LEAD_INVESTOR_DETAIL_SAVE_INIT = 'PATRON_LEAD:INVESTOR:DETAIL_SAVE:INIT';
const PATRON_LEAD_INVESTOR_DETAIL_SAVE_SUCCESS = 'PATRON_LEAD:INVESTOR:DETAIL_SAVE:SUCCESS';
const PATRON_LEAD_INVESTOR_DETAIL_SAVE_FAIL = 'PATRON_LEAD:INVESTOR:DETAIL_SAVE:FAIL';
const PATRON_LEAD_COMMUNICATIONS_DETAIL_FETCH_INIT = 'PATRON_LEAD:COMMUNICATIONS:DETAIL_FETCH:INIT';
const PATRON_LEAD_COMMUNICATIONS_DETAIL_FETCH_SUCCESS = 'PATRON_LEAD:COMMUNICATIONS:DETAIL_FETCH:SUCCESS';
const PATRON_LEAD_COMMUNICATIONS_DETAIL_FETCH_FAIL = 'PATRON_LEAD:COMMUNICATIONS:DETAIL_FETCH:FAIL';
const PATRON_LEAD_DOCUMENT_CONFIG_FETCH_INIT = 'PATRON_LEAD:DOCUMENT:CONFIG_FETCH:INIT';
const PATRON_LEAD_DOCUMENT_CONFIG_FETCH_SUCCESS = 'PATRON_LEAD:DOCUMENT:CONFIG_FETCH:SUCCESS';
const PATRON_LEAD_DOCUMENT_CONFIG_FETCH_FAIL = 'PATRON_LEAD:DOCUMENT:CONFIG_FETCH:FAIL';
const PATRON_LEAD_DOCUMENT_PRESIGNED_URL_FETCH_INIT = 'PATRON_LEAD:DOCUMENT:PRESIGNED_URL_FETCH:INIT';
const PATRON_LEAD_DOCUMENT_PRESIGNED_URL_FETCH_SUCCESS = 'PATRON_LEAD:DOCUMENT:PRESIGNED_URL_FETCH:SUCCESS';
const PATRON_LEAD_DOCUMENT_PRESIGNED_URL_FETCH_FAIL = 'PATRON_LEAD:DOCUMENT:PRESIGNED_URL_FETCH:FAIL';
const PATRON_LEAD_DOCUMENT_METADATA_POST_INIT = 'PATRON_LEAD:DOCUMENT:METADATA_POST:INIT';
const PATRON_LEAD_DOCUMENT_METADATA_POST_SUCCESS = 'PATRON_LEAD:DOCUMENT:METADATA_POST:SUCCESS';
const PATRON_LEAD_DOCUMENT_METADATA_POST_FAIL = 'PATRON_LEAD:DOCUMENT:METADATA_POST:FAIL';
const PATRON_LEAD_DOCUMENT_LIST_FETCH_INIT = 'PATRON_LEAD:DOCUMENT:LIST_FETCH:INIT';
const PATRON_LEAD_DOCUMENT_LIST_FETCH_SUCCESS = 'PATRON_LEAD:DOCUMENT:LIST_FETCH:SUCCESS';
const PATRON_LEAD_DOCUMENT_LIST_FETCH_FAIL = 'PATRON_LEAD:DOCUMENT:LIST_FETCH:FAIL';
const PATRON_LEAD_META_DATA_SAVE = 'PATRON_LEAD:METADATA:SAVE';
const PATRON_STATUS_UPDATE_INIT = 'PATRON:STATUS_UPDATE:INIT';
const PATRON_STATUS_UPDATE_SUCCESS = 'PATRON:STATUS_UPDATE:SUCCESS';
const PATRON_STATUS_UPDATE_FAIL = 'PATRON:STATUS_UPDATE:FAIL';
const GENERIC_CLEAR_PHONES = 'GENERIC:CLEAR_PHONES';
const GENERIC_CLEAR_EMAILS = 'GENERIC:CLEAR_EMAILS';
const GENERIC_CLEAR_ADDRESSES = 'GENERIC:CLEAR_ADDRESSES';

const DOCUMENT_FILE_VIEW_INIT = 'DOCUMENT:FILE_VIEW:INIT';
const DOCUMENT_FILE_VIEW_SUCCESS = 'DOCUMENT:FILE_VIEW:SUCCESS';
const DOCUMENT_FILE_VIEW_FAIL = 'DOCUMENT:FILE_VIEW:FAIL';
const DOCUMENT_FILE_DELETE_INIT = 'DOCUMENT:FILE_DELETE:INIT';
const DOCUMENT_FILE_DELETE_SUCCESS = 'DOCUMENT:FILE_DELETE:SUCCESS';
const DOCUMENT_FILE_DELETE_FAIL = 'DOCUMENT:FILE_DELETE:FAIL';

const DEAL_CREATE_DEAL_INIT = 'DEAL:CREATE_LEAD:INIT';
const DEAL_CREATE_DEAL_SUCCESS = 'DEAL:CREATE_LEAD:SUCCESS';
const DEAL_CREATE_DEAL_FAIL = 'DEAL:CREATE_LEAD:FAIL';
const DEAL_DATA_GENERIC_CONFIG_FETCH_INIT = 'DEAL_DATA:GENERIC_CONFIG:FETCH:INIT';
const DEAL_DATA_GENERIC_CONFIG_FETCH_SUCCESS = 'DEAL_DATA:GENERIC_CONFIG:FETCH:SUCCESS';
const DEAL_DATA_GENERIC_CONFIG_FETCH_FAIL = 'DEAL_DATA:GENERIC_CONFIG:FETCH:FAIL';
const DEAL_DATA_CONFIG_FETCH_INIT = 'DEAL_DATA:CONFIG:FETCH:INIT';
const DEAL_DATA_CONFIG_FETCH_SUCCESS = 'DEAL_DATA:CONFIG:FETCH:SUCCESS';
const DEAL_DATA_CONFIG_FETCH_FAIL = 'DEAL_DATA:CONFIG:FETCH:FAIL';
const DEAL_LIST_FETCH_INIT = 'DEAL_LIST:FETCH:INIT';
const DEAL_LIST_FETCH_SUCCESS = 'DEAL_LIST:FETCH:SUCCESS';
const DEAL_LIST_FETCH_FAIL = 'DEAL_LIST:FETCH:FAIL';
const DEAL_DETAIL_FETCH_INIT = 'DEAL_DETAIL:FETCH:INIT';
const DEAL_DETAIL_FETCH_SUCCESS = 'DEAL_DETAIL:FETCH:SUCCESS';
const DEAL_DETAIL_FETCH_FAIL = 'DEAL_DETAIL:FETCH:FAIL';
const DEAL_DETAIL_UPDATE_INIT = 'DEAL_DETAIL:UPDATE:INIT';
const DEAL_DETAIL_UPDATE_SUCCESS = 'DEAL_DETAIL:UPDATE:SUCCESS';
const DEAL_DETAIL_UPDATE_FAIL = 'DEAL_DETAIL:UPDATE:FAIL';
const DEAL_CREATE_DOCUMENT_PRESIGNED_URL_FETCH_INIT = 'DEAL_CREATE:DOCUMENT:PRESIGNED_URL:FETCH:INIT';
const DEAL_CREATE_DOCUMENT_PRESIGNED_URL_FETCH_SUCCESS = 'DEAL_CREATE:DOCUMENT:PRESIGNED_URL:FETCH:SUCCESS';
const DEAL_CREATE_DOCUMENT_PRESIGNED_URL_FETCH_FAIL = 'DEAL_CREATE:DOCUMENT:PRESIGNED_URL:FETCH:FAIL';
const DEAL_CREATE_DOCUMENT_METADATA_POST_INIT = 'DEAL_CREATE:DOCUMENT:METADATA:POST:INIT';
const DEAL_CREATE_DOCUMENT_METADATA_POST_SUCCESS = 'DEAL_CREATE:DOCUMENT:METADATA:POST:SUCCESS';
const DEAL_CREATE_DOCUMENT_METADATA_POST_FAIL = 'DEAL_CREATE:DOCUMENT:METADATA:POST:FAIL';
const DEAL_CREATE_DOCUMENT_LIST_FETCH_INIT = 'DEAL_CREATE:DOCUMENT:LIST:FETCH:INIT';
const DEAL_CREATE_DOCUMENT_LIST_FETCH_SUCCESS = 'DEAL_CREATE:DOCUMENT:LIST:FETCH:SUCCESS';
const DEAL_CREATE_DOCUMENT_LIST_FETCH_FAIL = 'DEAL_CREATE:DOCUMENT:LIST:FETCH:FAIL';
const DEAL_CREATE_DOCUMENT_FILE_VIEW_INIT = 'DEAL_CREATE:DOCUMENT:FILE:VIEW:INIT';
const DEAL_CREATE_DOCUMENT_FILE_VIEW_SUCCESS = 'DEAL_CREATE:DOCUMENT:FILE:VIEW:SUCCESS';
const DEAL_CREATE_DOCUMENT_FILE_VIEW_FAIL = 'DEAL_CREATE:DOCUMENT:FILE:VIEW:FAIL';
const DEAL_CREATE_DOCUMENT_FILE_DELETE_INIT = 'DEAL_CREATE:DOCUMENT:FILE:DELETE:INIT';
const DEAL_CREATE_DOCUMENT_FILE_DELETE_SUCCESS = 'DEAL_CREATE:DOCUMENT:FILE:DELETE:SUCCESS';
const DEAL_CREATE_DOCUMENT_FILE_DELETE_FAIL = 'DEAL_CREATE:DOCUMENT:FILE:DELETE:FAIL';
const DEAL_STATUS_UPDATE_INIT = 'DEAL_STATUS:UPDATE:INIT';
const DEAL_STATUS_UPDATE_SUCCESS = 'DEAL_STATUS:UPDATE:SUCCESS';
const DEAL_STATUS_UPDATE_FAIL = 'DEAL_STATUS:UPDATE:FAIL';
const DEAL_DOCUMENT_FETCH_INIT = 'DEAL_DOCUMET:FETCH:INIT';
const DEAL_DOCUMENT_FETCH_SUCCESS = 'DEAL_DOCUMENT:FETCH:SUCCESS';
const DEAL_DOCUMENT_FETCH_FAIL = 'DEAL_DOCUMENT:FETCH:FAIL';
const DEAL_DOCUMENT_TYPE_FETCH_INIT = 'DEAL_DOCUMET:TYPE_FETCH:INIT';
const DEAL_DOCUMENT_TYPE_FETCH_SUCCESS = 'DEAL_DOCUMENT:TYPE_FETCH:SUCCESS';
const DEAL_DOCUMENT_TYPE_FETCH_FAIL = 'DEAL_DOCUMENT:TYPE_FETCH:FAIL';

const HOMEPAGE_DUMMY_DATA_FETCH_REQUEST = 'HOMEPAGE:DUMMY_DATA:FETCH:REQUEST';
const HOMEPAGE_DUMMY_DATA_FETCH_SUCCESS = 'HOMEPAGE:DUMMY_DATA:FETCH:SUCCESS';
const HOMEPAGE_DUMMY_DATA_FETCH_FAIL = 'HOMEPAGE:DUMMY_DATA:FETCH:FAIL';

const GENERIC_REMARK_CREATE_INIT = 'GENERIC:CREATE_REMARK:INIT';
const GENERIC_REMARK_CREATE_SUCCESS = 'GENERIC:CREATE_REMARK:SUCCESS';
const GENERIC_REMARK_CREATE_FAIL = 'GENERIC:CREATE_REMARK:FAIL';
const GENERIC_REMARKS_GET_INIT = 'GENERIC:FETCH_REMARKS:INIT';
const GENERIC_REMARKS_GET_SUCCESS = 'GENERIC:FETCH_REMARKS:SUCCESS';
const GENERIC_REMARKS_GET_FAIL = 'GENERIC:FETCH_REMARKS:FAIL';
const GENERIC_REMARKS_SET_OFFSET = 'GENERIC:REMARKS:SET_OFFSET';

// Loyalty Module
const LOYALTY_REWARD_FETCH_INIT = 'LOYALTY:REWARD:FECTH_INIT';
const LOYALTY_REWARD_FETCH_SUCCESS = 'LOYALTY:REWARD:FECTH_SUCCESS';
const LOYALTY_REWARD_FETCH_FAIL = 'LOYALTY:REWARD:FECTH_FAIL';

const LOYALTY_REWARD_CREATE_INIT = 'LOYALTY:REWARD:CREATE_INIT';
const LOYALTY_REWARD_CREATE_SUCCESS = 'LOYALTY:REWARD:CREATE_SUCCESS';
const LOYALTY_REWARD_CREATE_FAIL = 'LOYALTY:REWARD:CREATE_FAIL';

const LOYALTY_REWARD_DETAIL_FETCH_INIT = 'LOYALTY:REWARD:DETAIL_FECTH_INIT';
const LOYALTY_REWARD_DETAIL_FETCH_SUCCESS = 'LOYALTY:REWARD:DETAIL_FECTH_SUCCESS';
const LOYALTY_REWARD_DETAIL_FETCH_FAIL = 'LOYALTY:REWARD:DETAIL_FECTH_FAIL';

const LOYALTY_REWARD_UPDATE_INIT = 'LOYALTY:REWARD:UPDATE_INIT';
const LOYALTY_REWARD_UPDATE_SUCCESS = 'LOYALTY:REWARD:UPDATE_SUCCESS';
const LOYALTY_REWARD_UPDATE_FAIL = 'LOYALTY:REWARD:UPDATE_FAIL';

const LOYALTY_REWARD_STATUS_UPDATE_INIT = 'LOYALTY:REWARD:STATUS:UPDATE_INIT';
const LOYALTY_REWARD_STATUS_UPDATE_SUCCESS = 'LOYALTY:REWARD:STATUS:UPDATE_SUCCESS';
const LOYALTY_REWARD_STATUS_UPDATE_FAIL = 'LOYALTY:REWARD:STATUS:UPDATE_FAIL';

const LOYALTY_POINT_FETCH_INIT = 'LOYALTY:POINT:FECTH_INIT';
const LOYALTY_POINT_FETCH_SUCCESS = 'LOYALTY:POINT:FECTH_SUCCESS';
const LOYALTY_POINT_FETCH_FAIL = 'LOYALTY:POINT:FETCH_FAIL';

const LOYALTY_POINT_CREATE_INIT = 'LOYALTY:POINT:CREATE_INIT';
const LOYALTY_POINT_CREATE_SUCCESS = 'LOYALTY:POINT:CREATE_SUCCESS';
const LOYALTY_POINT_CREATE_FAIL = 'LOYALTY:POINT:CREATE_FAIL';

const LOYALTY_POINT_DETAIL_FETCH_INIT = 'LOYALTY:POINT:DETAIL_FETCH_INIT';
const LOYALTY_POINT_DETAIL_FETCH_SUCCESS = 'LOYALTY:POINT:DETAIL_FETCH_SUCCESS';
const LOYALTY_POINT_DETAIL_FETCH_FAIL = 'LOYALTY:POINT:DETAIL_FETCH_FAIL';

const LOYALTY_POINT_UPDATE_INIT = 'LOYALTY:POINT:UPDATE_INIT';
const LOYALTY_POINT_UPDATE_SUCCESS = 'LOYALTY:POINT:UPDATE_SUCCESS';
const LOYALTY_POINT_UPDATE_FAIL = 'LOYALTY:POINT:UPDATE_FAIL';

const BRAND_LIST_FETCH_INIT = 'BRAND:LIST:FETCH:INIT';
const BRAND_LIST_FETCH_SUCCESS = 'BRAND:LIST:FETCH:SUCCESS';
const BRAND_LIST_FETCH_FAIL = 'BRAND:LIST:FETCH:FAIL';

const CUSTOMER_LIST_FETCH_INIT = 'CUSTOMER:LIST:FETCH:INIT';
const CUSTOMER_LIST_FETCH_SUCCESS = 'CUSTOMER:LIST:FETCH:SUCCESS';
const CUSTOMER_LIST_FETCH_FAIL = 'CUSTOMER:LIST:FETCH:FAIL';

const PATRON_LIST_FETCH_INIT = 'PATRON:LIST:FETCH:INIT';
const PATRON_LIST_FETCH_SUCCESS = 'PATRON:LIST:FETCH:SUCCESS';
const PATRON_LIST_FETCH_FAIL = 'PATRON:LIST:FETCH:FAIL';

const PATRON_BANK_DETAILS_INIT = 'PATRON:BANK:DETAILS:INIT';
const PATRON_BANK_DETAILS_SUCCESS = 'PATRON:BANK:DETAILS:SUCCESS';
const PATRON_BANK_DETAILS_FAIL = 'PATRON:BANK:DETAILS:FAIL';

const DEAL_INVESTMENT_FETCH_INIT = 'DEAL:INVESTMENT:FETCH:INIT';
const DEAL_INVESTMENT_FETCH_SUCCESS = 'DEAL:INVESTMENT:FETCH:SUCCESS';
const DEAL_INVESTMENT_FETCH_FAIL = 'DEAL:INVESTMENT:FETCH:FAIL';

const DEAL_INVESTMENT_CREATE_INIT = 'DEAL:INVESTMENT:CREATE:INIT';
const DEAL_INVESTMENT_CREATE_SUCCESS = 'DEAL:INVESTMENT:CREATE:SUCCESS';
const DEAL_INVESTMENT_CREATE_FAIL = 'DEAL:INVESTMENT:CREATE:FAIL';

const DEAL_INVESTMENT_DETAIL_FETCH_INIT = 'DEAL:INVESTMENT:DETAIL_FETCH:INIT';
const DEAL_INVESTMENT_DETAIL_FETCH_SUCCESS = 'DEAL:INVESTMENT:DETAIL_FETCH:SUCCESS';
const DEAL_INVESTMENT_DETAIL_FETCH_FAIL = 'DEAL:INVESTMENT:DETAIL_FETCH:FAIL';

const DEAL_INVESTMENT_UPDATE_INIT = 'DEAL:INVESTMENT:UPDATE:INIT';
const DEAL_INVESTMENT_UPDATE_SUCCESS = 'DEAL:INVESTMENT:UPDATE:SUCCESS';
const DEAL_INVESTMENT_UPDATE_FAIL = 'DEAL:INVESTMENT:UPDATE:FAIL';

const DEAL_INVESTMENT_STATUS_UPDATE_INIT = 'DEAL:INVESTMENT:STATUS:UPDATE:INIT';
const DEAL_INVESTMENT_STATUS_UPDATE_SUCCESS = 'DEAL:INVESTMENT:STATUS:UPDATE:SUCCESS';
const DEAL_INVESTMENT_STATUS_UPDATE_FAIL = 'DEAL:INVESTMENT:STATUS:UPDATE:FAIL';
const DEAL_DOC_CONFIG_INIT = 'DEAL:DOC:CONFIG:INIT';
const DEAL_DOC_CONFIG_SUCCESS = 'DEAL:DOC:CONFIG:SUCCESS';
const DEAL_DOC_CONFIG_FAIL = 'DEAL:DOC:CONFIG:FAIL';
const DEAL_SINGLE_SECTION_UPDATE_SUCCESS = 'DEAL:SINGLE_SECTION_UPDATE:SUCCESS';
const DEAL_SINGLE_SECTION_UPDATE_INIT = 'DEAL:SINGLE_SECTION_UPDATE:INIT';
const DEAL_SINGLE_SECTION_UPDATE_FAIL = 'DEAL:SINGLE_SECTION_UPDATE:FAIL';
const DEAL_SECTIONS_FETCH_SUCCESS = 'DEAL_SINGLE_SECTIONS:FETCH:SUCCESS';
const DEAL_SECTIONS_FETCH_FAIL = 'DEAL_SINGLE_SECTIONS:FETCH:FAIL';
const DEAL_GROUP_FETCH_SUCCESS = 'DEAL_SECTIONS_GROUP:FETCH:SUCCESS';
const DEAL_GROUP_FETCH_FAIL = 'DEAL_SECTIONS_GROUP:FETCH:FAIL';
const DEAL_SINGLE_FIELD_UPDATE = 'DEAL_SECTION_FIELD:UPDATE';
const DEAL_DOCUMENT_VALIDATION_UPDATE = 'DEAL_DOCUMENT_VALIDATION:UPDATE';

export {
  HOMEPAGE_DUMMY_DATA_FETCH_REQUEST,
  HOMEPAGE_DUMMY_DATA_FETCH_SUCCESS,
  HOMEPAGE_DUMMY_DATA_FETCH_FAIL,

  BRAND_LEAD_APPLICANT_CREATE_INIT,
  BRAND_LEAD_APPLICANT_CREATE_SUCCESS,
  BRAND_LEAD_APPLICANT_CREATE_FAIL,
  // BRAND_LEAD_LIST_FETCH_INIT,
  // BRAND_LEAD_LIST_FETCH_SUCCESS,
  // BRAND_LEAD_LIST_FETCH_FAIL,

  BRAND_LEAD_APPLICATION_DETAIL_FETCH_INIT,
  BRAND_LEAD_APPLICATION_DETAIL_FETCH_SUCCESS,
  BRAND_LEAD_APPLICATION_DETAIL_FETCH_FAIL,
  BRAND_LEAD_APPLICANT_DETAIL_UPDATE_INIT,
  BRAND_LEAD_APPLICANT_DETAIL_UPDATE_SUCCESS,
  BRAND_LEAD_APPLICANT_DETAIL_UPDATE_FAIL,
  BRAND_LEAD_BUSINESS_DETAIL_UPDATE_INIT,
  BRAND_LEAD_BUSINESS_DETAIL_UPDATE_SUCCESS,
  BRAND_LEAD_BUSINESS_DETAIL_UPDATE_FAIL,
  BRAND_LEAD_BRAND_DETAIL_UPDATE_INIT,
  BRAND_LEAD_BRAND_DETAIL_UPDATE_SUCCESS,
  BRAND_LEAD_BRAND_DETAIL_UPDATE_FAIL,
  BRAND_LEAD_BRAND_STATUS_UPDATE_INIT,
  BRAND_LEAD_BRAND_STATUS_UPDATE_SUCCESS,
  BRAND_LEAD_BRAND_STATUS_UPDATE_FAIL,
  BRAND_LEAD_DETAIL_UPDATE_CLEAR,
  BRAND_LEAD_BRAND_DOCUMENT_CONFIG_FETCH_INIT,
  BRAND_LEAD_BRAND_DOCUMENT_CONFIG_FETCH_SUCCESS,
  BRAND_LEAD_BRAND_DOCUMENT_CONFIG_FETCH_FAIL,
  BRAND_LEAD_BRAND_DOCUMENT_PRESIGNED_URL_FETCH_INIT,
  BRAND_LEAD_BRAND_DOCUMENT_PRESIGNED_URL_FETCH_SUCCESS,
  BRAND_LEAD_BRAND_DOCUMENT_PRESIGNED_URL_FETCH_FAIL,
  BRAND_LEAD_BRAND_DOCUMENT_METADATA_POST_INIT,
  BRAND_LEAD_BRAND_DOCUMENT_METADATA_POST_SUCCESS,
  BRAND_LEAD_BRAND_DOCUMENT_METADATA_POST_FAIL,
  BRAND_LEAD_BRAND_DOCUMENT_LIST_FETCH_INIT,
  BRAND_LEAD_BRAND_DOCUMENT_LIST_FETCH_SUCCESS,
  BRAND_LEAD_BRAND_DOCUMENT_LIST_FETCH_FAIL,
  BRAND_LEAD_BRAND_DOCUMENT_STATUS_UPDATE_INIT,
  BRAND_LEAD_BRAND_DOCUMENT_STATUS_UPDATE_SUCCESS,
  BRAND_LEAD_BRAND_DOCUMENT_STATUS_UPDATE_FAIL,
  BRAND_LEAD_DOCUMENT_FILE_VIEW_INIT,
  BRAND_LEAD_DOCUMENT_FILE_VIEW_SUCCESS,
  BRAND_LEAD_DOCUMENT_FILE_VIEW_FAIL,
  BRAND_LEAD_DOCUMENT_FILE_DELETE_INIT,
  BRAND_LEAD_DOCUMENT_FILE_DELETE_SUCCESS,
  BRAND_LEAD_DOCUMENT_FILE_DELETE_FAIL,
  BRAND_LEAD_DOCUMENT_CONFIG_DATA_CLEAR,

  // brands-v2
  BRAND_LEAD_DETAIL_FORM_UPDATE_INIT,
  BRAND_LEAD_DETAIL_FORM_UPDATE_SUCCESS,
  BRAND_LEAD_DETAIL_FORM_UPDATE_FAIL,
  BRAND_LEAD_APPLICANT_DETAIL_INIT,
  BRAND_LEAD_APPLICANT_DETAIL_SUCCESS,
  BRAND_LEAD_APPLICANT_DETAIL_FAIL,
  BRAND_LEAD_LIST_FETCH_INIT,
  BRAND_LEAD_LIST_FETCH_SUCCESS,
  BRAND_LEAD_LIST_FETCH_FAIL,
  BRAND_CREATE_BRAND_INIT,
  BRAND_CREATE_BRAND_SUCCESS,
  BRAND_CREATE_BRAND_FAIL,
  BRAND_LEAD_DETAIL_FETCH_INIT,
  BRAND_LEAD_DETAIL_FETCH_SUCCESS,
  BRAND_LEAD_DETAIL_FETCH_FAIL,
  BRAND_LEAD_PERFORMANCE_FETCH_INIT,
  BRAND_LEAD_PERFORMANCE_FETCH_SUCCESS,
  BRAND_LEAD_PERFORMANCE_FETCH_FAIL,
  BRAND_LEAD_PERFORMANCE_UPDATE_INIT,
  BRAND_LEAD_PERFORMANCE_UPDATE_SUCCESS,
  BRAND_LEAD_PERFORMANCE_UPDATE_FAIL,
  BRAND_LEAD_COMMUNICATIONS_DETAIL_FETCH_INIT,
  BRAND_LEAD_COMMUNICATIONS_DETAIL_FETCH_SUCCESS,
  BRAND_LEAD_COMMUNICATIONS_DETAIL_FETCH_FAIL,
  BRAND_COMMUNICATION_GET_ADDRESSES_INIT,
  BRAND_COMMUNICATION_GET_ADDRESSES_SUCCESS,
  BRAND_COMMUNICATION_GET_ADDRESSES_FAIL,
  BRAND_APPLICANT_LIST_FETCH_INIT,
  BRAND_APPLICANT_LIST_FETCH_SUCCESS,
  BRAND_APPLICANT_LIST_FETCH_FAIL,
  BRAND_BUSINESS_DETAILS_FETCH_INIT,
  BRAND_BUSINESS_DETAILS_FETCH_SUCCESS,
  BRAND_BUSINESS_DETAILS_FETCH_FAIL,
  BRAND_BUSINESS_DETAILS_UPDATE_INIT,
  BRAND_BUSINESS_DETAILS_UPDATE_SUCCESS,
  BRAND_BUSINESS_DETAILS_UPDATE_FAIL,
  BRAND_APPLICANT_BASIC_INFO_FETCH_INIT,
  BRAND_APPLICANT_BASIC_INFO_FETCH_SUCCESS,
  BRAND_APPLICANT_BASIC_INFO_FETCH_FAIL,
  BRAND_STATUS_UPDATE_INIT,
  BRAND_STATUS_UPDATE_SUCCESS,
  BRAND_STATUS_UPDATE__FAIL,
  BRAND_BANKING_BANKS_FETCH_INIT,
  BRAND_BANKING_BANKS_FETCH_SUCCESS,
  BRAND_BANKING_BANKS_FETCH_FAIL,
  BRAND_BANKING_ACCOUNTS_FETCH_INIT,
  BRAND_BANKING_ACCOUNTS_FETCH_SUCCESS,
  BRAND_BANKING_ACCOUNTS_FETCH_FAIL,
  BRAND_BANKING_ADD_ACCOUNT_INIT,
  BRAND_BANKING_ADD_ACCOUNT_SUCCESS,
  BRAND_BANKING_ADD_ACCOUNT_FAIL,
  BRAND_BANKING_UPDATE_ACCOUNT_INIT,
  BRAND_BANKING_UPDATE_ACCOUNT_SUCCESS,
  BRAND_BANKING_UPDATE_ACCOUNT_FAIL,
  BRAND_BANKING_DOCUMENT_FETCH_INIT,
  BRAND_BANKING_DOCUMENT_FETCH_SUCCESS,
  BRAND_BANKING_DOCUMENT_FETCH_FAIL,
  BRAND_BANKING_DOCUMENT_TYPE_FETCH_INIT,
  BRAND_BANKING_DOCUMENT_TYPE_FETCH_SUCCESS,
  BRAND_BANKING_DOCUMENT_TYPE_FETCH_FAIL,
  BRAND_APPLICANT_INFO_STORE,
  BRAND_BANKING_CLEAR_ACCOUNTS,
  BRAND_BANKING_DOCUMENT_PARSE_INIT,
  BRAND_BANKING_DOCUMENT_PARSE_SUCCESS,
  BRAND_BANKING_DOCUMENT_PARSE_FAIL,

  // Brand Financial
  BRAND_FINANCIAL_OVERVIEW_FETCH_INIT,
  BRAND_FINANCIAL_OVERVIEW_FETCH_SUCCESS,
  BRAND_FINANCIAL_OVERVIEW_FETCH_FAIL,
  BRAND_FINANCIAL_SHAREHOLDING_FETCH_INIT,
  BRAND_FINANCIAL_SHAREHOLDING_FETCH_SUCCESS,
  BRAND_FINANCIAL_SHAREHOLDING_FETCH_FAIL,
  BRAND_FINANCIAL_SHAREHOLDING_SUMMARY_FETCH_INIT,
  BRAND_FINANCIAL_SHAREHOLDING_SUMMARY_FETCH_SUCCESS,
  BRAND_FINANCIAL_SHAREHOLDING_SUMMARY_FETCH_FAIL,
  BRAND_FINANCIAL_SECURITIES_ALLOTMENT_FETCH_INIT,
  BRAND_FINANCIAL_SECURITIES_ALLOTMENT_FETCH_SUCCESS,
  BRAND_FINANCIAL_SECURITIES_ALLOTMENT_FETCH_FAIL,
  BRAND_FINANCIAL_PROFIT_AND_LOSS_FETCH_INIT,
  BRAND_FINANCIAL_PROFIT_AND_LOSS_FETCH_SUCCESS,
  BRAND_FINANCIAL_PROFIT_AND_LOSS_FETCH_FAIL,
  BRAND_FINANCIAL_BALANCE_SHEET_FETCH_INIT,
  BRAND_FINANCIAL_BALANCE_SHEET_FETCH_SUCCESS,
  BRAND_FINANCIAL_BALANCE_SHEET_FETCH_FAIL,
  BRAND_FINANCIAL_CASH_FLOW_FETCH_INIT,
  BRAND_FINANCIAL_CASH_FLOW_FETCH_SUCCESS,
  BRAND_FINANCIAL_CASH_FLOW_FETCH_FAIL,
  BRAND_FINANCIAL_CHARGES_FETCH_INIT,
  BRAND_FINANCIAL_CHARGES_FETCH_SUCCESS,
  BRAND_FINANCIAL_CHARGES_FETCH_FAIL,
  BRAND_FINANCIAL_LEGAL_HISTORY_FETCH_INIT,
  BRAND_FINANCIAL_LEGAL_HISTORY_FETCH_SUCCESS,
  BRAND_FINANCIAL_LEGAL_HISTORY_FETCH_FAIL,
  BRANDS_FETCH_FINANCIALS_INIT,
  BRANDS_FETCH_FINANCIALS_SUCCESS,
  BRANDS_FETCH_FINANCIALS_FAIL,

  PATRON_LEAD_APPLICANT_CREATE_INIT,
  PATRON_LEAD_APPLICANT_CREATE_SUCCESS,
  PATRON_LEAD_APPLICANT_CREATE_FAIL,
  PATRON_LEAD_PATRON_DETAIL_FETCH_INIT,
  PATRON_LEAD_PATRON_DETAIL_FETCH_SUCCESS,
  PATRON_LEAD_PATRON_DETAIL_FETCH_FAIL,
  PATRON_LEAD_APPLICATION_DETAIL_UPDATE_INIT,
  PATRON_LEAD_APPLICATION_DETAIL_UPDATE_SUCCESS,
  PATRON_LEAD_APPLICATION_DETAIL_UPDATE_FAIL,
  PATRON_LEAD_ENTITY_DETAIL_UPDATE_INIT,
  PATRON_LEAD_ENTITY_DETAIL_UPDATE_SUCCESS,
  PATRON_LEAD_ENTITY_DETAIL_UPDATE_FAIL,
  PATRON_LEAD_PATRON_STATUS_UPDATE_INIT,
  PATRON_LEAD_PATRON_STATUS_UPDATE_SUCCESS,
  PATRON_LEAD_PATRON_STATUS_UPDATE_FAIL,
  PATRON_LEAD_DETAIL_UPDATE_CLEAR,
  PATRON_LEAD_PATRON_DOCUMENT_CONFIG_FETCH_INIT,
  PATRON_LEAD_PATRON_DOCUMENT_CONFIG_FETCH_SUCCESS,
  PATRON_LEAD_PATRON_DOCUMENT_CONFIG_FETCH_FAIL,
  PATRON_LEAD_PATRON_DOCUMENT_PRESIGNED_URL_FETCH_INIT,
  PATRON_LEAD_PATRON_DOCUMENT_PRESIGNED_URL_FETCH_SUCCESS,
  PATRON_LEAD_PATRON_DOCUMENT_PRESIGNED_URL_FETCH_FAIL,
  PATRON_LEAD_PATRON_DOCUMENT_METADATA_POST_INIT,
  PATRON_LEAD_PATRON_DOCUMENT_METADATA_POST_SUCCESS,
  PATRON_LEAD_PATRON_DOCUMENT_METADATA_POST_FAIL,
  PATRON_LEAD_PATRON_DOCUMENT_LIST_FETCH_INIT,
  PATRON_LEAD_PATRON_DOCUMENT_LIST_FETCH_SUCCESS,
  PATRON_LEAD_PATRON_DOCUMENT_LIST_FETCH_FAIL,
  PATRON_LEAD_DOCUMENT_FILE_VIEW_INIT,
  PATRON_LEAD_DOCUMENT_FILE_VIEW_SUCCESS,
  PATRON_LEAD_DOCUMENT_FILE_VIEW_FAIL,
  PATRON_LEAD_DOCUMENT_FILE_DELETE_INIT,
  PATRON_LEAD_DOCUMENT_FILE_DELETE_SUCCESS,
  PATRON_LEAD_DOCUMENT_FILE_DELETE_FAIL,
  PATRON_LEAD_DOCUMENT_CONFIG_DATA_CLEAR,
  PATRON_LEAD_PATRON_DOCUMENT_STATUS_UPDATE_INIT,
  PATRON_LEAD_PATRON_DOCUMENT_STATUS_UPDATE_SUCCESS,
  PATRON_LEAD_PATRON_DOCUMENT_STATUS_UPDATE_FAIL,

  // patrons

  PATRON_LEAD_LIST_FETCH_INIT,
  PATRON_LEAD_LIST_FETCH_SUCCESS,
  PATRON_LEAD_LIST_FETCH_FAIL,
  PATRON_CREATE_PATRON_INIT,
  PATRON_CREATE_PATRON_SUCCESS,
  PATRON_CREATE_PATRON_FAIL,
  GENERIC_ADD_NUMBER_INIT,
  GENERIC_ADD_NUMBER_SUCCESS,
  GENERIC_ADD_NUMBER_FAIL,
  GENERIC_ADD_EMAIL_INIT,
  GENERIC_ADD_EMAIL_SUCCESS,
  GENERIC_ADD_EMAIL_FAIL,
  GENERIC_ADD_ADDRESS_INIT,
  GENERIC_ADD_ADDRESS_SUCCESS,
  GENERIC_ADD_ADDRESS_FAIL,
  GENERIC_GET_PHONES_INIT,
  GENERIC_GET_PHONES_SUCCESS,
  GENERIC_GET_PHONES_FAIL,
  GENERIC_GET_EMAILS_INIT,
  GENERIC_GET_EMAILS_SUCCESS,
  GENERIC_GET_EMAILS_FAIL,
  GENERIC_UPDATE_NUMBER_INIT,
  GENERIC_UPDATE_NUMBER_SUCCESS,
  GENERIC_UPDATE_NUMBER_FAIL,
  GENERIC_UPDATE_EMAIL_INIT,
  GENERIC_UPDATE_EMAIL_SUCCESS,
  GENERIC_UPDATE_EMAIL_FAIL,
  GENERIC_GET_ADDRESSES_INIT,
  GENERIC_GET_ADDRESSES_SUCCESS,
  GENERIC_GET_ADDRESSES_FAIL,
  GENERIC_UPDATE_ADDRESS_INIT,
  GENERIC_UPDATE_ADDRESS_SUCCESS,
  GENERIC_UPDATE_ADDRESS_FAIL,
  PATRON_LEAD_DETAIL_FETCH_INIT,
  PATRON_LEAD_DETAIL_FETCH_SUCCESS,
  PATRON_LEAD_DETAIL_FETCH_FAIL,
  PATRON_LEAD_CUSTOMER_DETAIL_FETCH_INIT,
  PATRON_LEAD_CUSTOMER_DETAIL_FETCH_SUCCESS,
  PATRON_LEAD_CUSTOMER_DETAIL_FETCH_FAIL,
  PATRON_LEAD_INVESTOR_DETAIL_FETCH_INIT,
  PATRON_LEAD_INVESTOR_DETAIL_FETCH_SUCCESS,
  PATRON_LEAD_INVESTOR_DETAIL_FETCH_FAIL,
  PATRON_LEAD_CUSTOMER_DETAIL_SAVE_INIT,
  PATRON_LEAD_CUSTOMER_DETAIL_SAVE_SUCCESS,
  PATRON_LEAD_CUSTOMER_DETAIL_SAVE_FAIL,
  PATRON_LEAD_INVESTOR_DETAIL_SAVE_INIT,
  PATRON_LEAD_INVESTOR_DETAIL_SAVE_SUCCESS,
  PATRON_LEAD_INVESTOR_DETAIL_SAVE_FAIL,
  PATRON_LEAD_COMMUNICATIONS_DETAIL_FETCH_INIT,
  PATRON_LEAD_COMMUNICATIONS_DETAIL_FETCH_SUCCESS,
  PATRON_LEAD_COMMUNICATIONS_DETAIL_FETCH_FAIL,
  PATRON_LEAD_DOCUMENT_CONFIG_FETCH_INIT,
  PATRON_LEAD_DOCUMENT_CONFIG_FETCH_SUCCESS,
  PATRON_LEAD_DOCUMENT_CONFIG_FETCH_FAIL,
  PATRON_LEAD_DOCUMENT_PRESIGNED_URL_FETCH_INIT,
  PATRON_LEAD_DOCUMENT_PRESIGNED_URL_FETCH_SUCCESS,
  PATRON_LEAD_DOCUMENT_PRESIGNED_URL_FETCH_FAIL,
  PATRON_LEAD_META_DATA_SAVE,
  PATRON_LEAD_DOCUMENT_METADATA_POST_INIT,
  PATRON_LEAD_DOCUMENT_METADATA_POST_SUCCESS,
  PATRON_LEAD_DOCUMENT_METADATA_POST_FAIL,
  PATRON_LEAD_DOCUMENT_LIST_FETCH_INIT,
  PATRON_LEAD_DOCUMENT_LIST_FETCH_SUCCESS,
  PATRON_LEAD_DOCUMENT_LIST_FETCH_FAIL,
  PATRON_STATUS_UPDATE_INIT,
  PATRON_STATUS_UPDATE_SUCCESS,
  PATRON_STATUS_UPDATE_FAIL,
  GENERIC_CLEAR_PHONES,
  GENERIC_CLEAR_EMAILS,
  GENERIC_CLEAR_ADDRESSES,

  DOCUMENT_FILE_VIEW_INIT,
  DOCUMENT_FILE_VIEW_SUCCESS,
  DOCUMENT_FILE_VIEW_FAIL,
  DOCUMENT_FILE_DELETE_INIT,
  DOCUMENT_FILE_DELETE_SUCCESS,
  DOCUMENT_FILE_DELETE_FAIL,

  DEAL_CREATE_DEAL_INIT,
  DEAL_CREATE_DEAL_SUCCESS,
  DEAL_CREATE_DEAL_FAIL,
  DEAL_DATA_GENERIC_CONFIG_FETCH_INIT,
  DEAL_DATA_GENERIC_CONFIG_FETCH_SUCCESS,
  DEAL_DATA_GENERIC_CONFIG_FETCH_FAIL,
  DEAL_DATA_CONFIG_FETCH_INIT,
  DEAL_DATA_CONFIG_FETCH_SUCCESS,
  DEAL_DATA_CONFIG_FETCH_FAIL,
  DEAL_LIST_FETCH_INIT,
  DEAL_LIST_FETCH_SUCCESS,
  DEAL_LIST_FETCH_FAIL,
  DEAL_DETAIL_FETCH_INIT,
  DEAL_DETAIL_FETCH_SUCCESS,
  DEAL_DETAIL_FETCH_FAIL,
  DEAL_DETAIL_UPDATE_INIT,
  DEAL_DETAIL_UPDATE_SUCCESS,
  DEAL_DETAIL_UPDATE_FAIL,
  DEAL_CREATE_DOCUMENT_PRESIGNED_URL_FETCH_INIT,
  DEAL_CREATE_DOCUMENT_PRESIGNED_URL_FETCH_SUCCESS,
  DEAL_CREATE_DOCUMENT_PRESIGNED_URL_FETCH_FAIL,
  DEAL_CREATE_DOCUMENT_METADATA_POST_INIT,
  DEAL_CREATE_DOCUMENT_METADATA_POST_SUCCESS,
  DEAL_CREATE_DOCUMENT_METADATA_POST_FAIL,
  DEAL_CREATE_DOCUMENT_LIST_FETCH_INIT,
  DEAL_CREATE_DOCUMENT_LIST_FETCH_SUCCESS,
  DEAL_CREATE_DOCUMENT_LIST_FETCH_FAIL,
  DEAL_CREATE_DOCUMENT_FILE_VIEW_INIT,
  DEAL_CREATE_DOCUMENT_FILE_VIEW_SUCCESS,
  DEAL_CREATE_DOCUMENT_FILE_VIEW_FAIL,
  DEAL_CREATE_DOCUMENT_FILE_DELETE_INIT,
  DEAL_CREATE_DOCUMENT_FILE_DELETE_SUCCESS,
  DEAL_CREATE_DOCUMENT_FILE_DELETE_FAIL,
  DEAL_STATUS_UPDATE_INIT,
  DEAL_STATUS_UPDATE_SUCCESS,
  DEAL_STATUS_UPDATE_FAIL,
  DEAL_DOCUMENT_FETCH_INIT,
  DEAL_DOCUMENT_FETCH_SUCCESS,
  DEAL_DOCUMENT_FETCH_FAIL,
  DEAL_DOCUMENT_TYPE_FETCH_INIT,
  DEAL_DOCUMENT_TYPE_FETCH_SUCCESS,
  DEAL_DOCUMENT_TYPE_FETCH_FAIL,
  DEAL_GROUP_FETCH_SUCCESS,
  DEAL_GROUP_FETCH_FAIL,
  DEAL_SINGLE_FIELD_UPDATE,
  DEAL_DOCUMENT_VALIDATION_UPDATE,

  GENERIC_REMARK_CREATE_INIT,
  GENERIC_REMARK_CREATE_SUCCESS,
  GENERIC_REMARK_CREATE_FAIL,
  GENERIC_REMARKS_GET_INIT,
  GENERIC_REMARKS_GET_SUCCESS,
  GENERIC_REMARKS_GET_FAIL,
  GENERIC_REMARKS_SET_OFFSET,

  // Loyalty Module
  LOYALTY_REWARD_FETCH_INIT,
  LOYALTY_REWARD_FETCH_SUCCESS,
  LOYALTY_REWARD_FETCH_FAIL,

  LOYALTY_REWARD_CREATE_INIT,
  LOYALTY_REWARD_CREATE_SUCCESS,
  LOYALTY_REWARD_CREATE_FAIL,

  LOYALTY_REWARD_DETAIL_FETCH_INIT,
  LOYALTY_REWARD_DETAIL_FETCH_SUCCESS,
  LOYALTY_REWARD_DETAIL_FETCH_FAIL,

  LOYALTY_REWARD_UPDATE_INIT,
  LOYALTY_REWARD_UPDATE_SUCCESS,
  LOYALTY_REWARD_UPDATE_FAIL,

  LOYALTY_REWARD_STATUS_UPDATE_INIT,
  LOYALTY_REWARD_STATUS_UPDATE_SUCCESS,
  LOYALTY_REWARD_STATUS_UPDATE_FAIL,

  LOYALTY_POINT_FETCH_INIT,
  LOYALTY_POINT_FETCH_SUCCESS,
  LOYALTY_POINT_FETCH_FAIL,

  LOYALTY_POINT_CREATE_INIT,
  LOYALTY_POINT_CREATE_SUCCESS,
  LOYALTY_POINT_CREATE_FAIL,

  LOYALTY_POINT_DETAIL_FETCH_INIT,
  LOYALTY_POINT_DETAIL_FETCH_SUCCESS,
  LOYALTY_POINT_DETAIL_FETCH_FAIL,

  LOYALTY_POINT_UPDATE_INIT,
  LOYALTY_POINT_UPDATE_SUCCESS,
  LOYALTY_POINT_UPDATE_FAIL,

  // brands
  BRAND_LIST_FETCH_INIT,
  BRAND_LIST_FETCH_SUCCESS,
  BRAND_LIST_FETCH_FAIL,

  // customers
  CUSTOMER_LIST_FETCH_INIT,
  CUSTOMER_LIST_FETCH_SUCCESS,
  CUSTOMER_LIST_FETCH_FAIL,

  // patrons
  PATRON_LIST_FETCH_INIT,
  PATRON_LIST_FETCH_SUCCESS,
  PATRON_LIST_FETCH_FAIL,

  PATRON_BANK_DETAILS_INIT,
  PATRON_BANK_DETAILS_SUCCESS,
  PATRON_BANK_DETAILS_FAIL,

  // Deal Investment
  DEAL_INVESTMENT_FETCH_INIT,
  DEAL_INVESTMENT_FETCH_SUCCESS,
  DEAL_INVESTMENT_FETCH_FAIL,

  DEAL_INVESTMENT_CREATE_INIT,
  DEAL_INVESTMENT_CREATE_SUCCESS,
  DEAL_INVESTMENT_CREATE_FAIL,

  DEAL_INVESTMENT_DETAIL_FETCH_INIT,
  DEAL_INVESTMENT_DETAIL_FETCH_SUCCESS,
  DEAL_INVESTMENT_DETAIL_FETCH_FAIL,

  DEAL_INVESTMENT_UPDATE_INIT,
  DEAL_INVESTMENT_UPDATE_SUCCESS,
  DEAL_INVESTMENT_UPDATE_FAIL,

  DEAL_INVESTMENT_STATUS_UPDATE_INIT,
  DEAL_INVESTMENT_STATUS_UPDATE_SUCCESS,
  DEAL_INVESTMENT_STATUS_UPDATE_FAIL,

  DEAL_DOC_CONFIG_INIT,
  DEAL_DOC_CONFIG_SUCCESS,
  DEAL_DOC_CONFIG_FAIL,
  DEAL_SINGLE_SECTION_UPDATE_SUCCESS,
  DEAL_SINGLE_SECTION_UPDATE_INIT,
  DEAL_SINGLE_SECTION_UPDATE_FAIL,
  DEAL_SECTIONS_FETCH_SUCCESS,
  DEAL_SECTIONS_FETCH_FAIL
};
